### ISSUE TITLE
Add functionality for multiple rounds in one day

### ISSUE THREAD

**Issue by kellyatkinson** [steveclifton/ArcheryOSA-v.3#13]
Currently "Event Competitions" just lets me choose one round (or set of rounds) in a day.

There are multiple times when I need to have separate competitions on a day:
- Any Double 720 tournament, because each is a separate event for purposes of ranking/records
- many indoor tournaments - allow a choice of one or more shooting sessions within a day

Due date: by 8-9 November (we have an IFAA indoor event coming up which would need this)

**Comment by kellyatkinson** [comment]
You've done this now @steveclifton

**Comment by steveclifton** [comment]
Have added :)
