### ISSUE TITLE
Create new type for age division

### ISSUE THREAD

**Issue by kellyatkinson** [steveclifton/ArcheryOSA-v.3#21]
At present, Divisions in AOSA are used to cover both age divisions (Cub, Kiwi, Veteran, Junior, etc) and bow types (Recurve, Compound, Bowhunter Limited, Historical Bow etc) across both target and field events.

This is too much complexity to try to put into a single set of fields, and it's unworkable with the IFAA bow class x age group division style. Plus I can't tell the similar target and field divisions (like Longbow) apart in the Admin list of Divisions because the Organisation isn't currently shown in the list view - otherwise I could see that one is the IFAA Longbow and one is the World Archery Longbow.

The existing list of Divisions will work for one or the other of these - just age groups or bow types. 

- Please create a second structure like this for the other one - bow types or age groups. 
- Make sure the list of divisions (in the manager side) shows the organisation too (ref [Issue 11](https://github.com/steveclifton/ArcheryOSA-v.3/issues/11) around making it clear to people that "organisation" = "the group that makes the rules for this kind of event"). 
- Allow managers to define which bow types AND which age groups can be selected for an event.

**Comment by steveclifton** [comment]
Have added this to divisions and division age groups
