### ISSUE TITLE
Archer entry first and surname are still lowercase - should be Sentence Case

### ISSUE THREAD

**Issue by kellyatkinson** [steveclifton/ArcheryOSA-v.3#23]
<img width="1335" alt="screenshot 2018-11-18 07 12 43" src="https://user-images.githubusercontent.com/8167044/48664294-58ac9480-eb01-11e8-90ea-190e0c03722c.png">

_Originally posted by @kellyatkinson in https://github.com/steveclifton/ArcheryOSA-v.3/issue_comments#issuecomment-439636632_

**Comment by steveclifton** [comment]
Data stored in the database is purposefully lowercased (as seen in the controller below).

I can make this uppercase in this module if preferred, but it will only be for aesthetics as it will be converted to lowercase again before being saved

https://github.com/steveclifton/ArcheryOSA-v.3/blob/master/app/Http/Controllers/Events/Auth/EventRegistrationController.php#L280

**Comment by kellyatkinson** [comment]
For the sake of aesthetics and societal conventions, I think Sentence Case will be very helpful. This will also be needed in the results csv output for Archery NZ too.

**Comment by steveclifton** [comment]
Ok has been updated 👍 
https://github.com/steveclifton/ArcheryOSA-v.3/commit/0e8a211b09c5c42c0c2c04da38296ac7be04fa36
