### ISSUE TITLE
Change archer "Membership" field title to "Membership Number"

### ISSUE THREAD

**Issue by kellyatkinson** [steveclifton/ArcheryOSA-v.3#26]
On an archer's entry, they see a box called "Membership" which is a free text type. Some people are STILL entering this incorrectly as they don't know that it's asking for their Archery NZ (or NZFAA) membership _number_.

Please change the title of this field to "Membership number" to make this more clear.

**Comment by steveclifton** [comment]
https://github.com/steveclifton/ArcheryOSA-v.3/commit/4e0266a6bf7e471d100533e8bee80d06aeb7ba57

Have updated
